### ISSUE TITLE
Planificacion

### ISSUE THREAD

**Issue by lewisnavarro** [lewisnavarro/Servicliente247#1]
- Creación de GitHub
- Asignación de tareas a usuarios

**Comment by lewisnavarro** [comment]
Se crearon las tareas propuestas por el equipo, se asignaron las pertenecientes al usuario de Geovanny

**Comment by lewisnavarro** [comment]
Se hicieron las asignaciones según el archivo de drive del compañero Geuner y se terminaron de asignar las tareas al resto del equipo

**Comment by mafer2871** [comment]
[Formatos Product-Sprint.xlsx](https://github.com/lewisnavarro/Servicliente247/files/7599014/Formatos.Product-Sprint.xlsx)

Se adjuntan los formatos de control de tareas y planificación
